#!/usr/bin/env python3
import json

# ALL MISSING TRANSLATION KEYS - organized by component
ALL_KEYS = {
    'en': {
        # FAQ Component (17 keys)
        'faqSectionTitle': 'Frequently Asked Questions',
        'faqSectionDesc': 'Everything you need to know about seasonal work and stays',
        'faq1Q': 'How does the 90-day free trial work?',
        'faq1A': 'Sign up for any paid plan and add your payment details. You get full access for 90 days completely free. Cancel anytime before the trial ends with no charges.',
        'faq2Q': 'What verification levels do I need?',
        'faq2A': 'Basic (free) users need email verification. Paid plans require phone verification for messaging. ID verification is optional but builds trust and unlocks premium features.',
        'faq3Q': 'How do I list my property or job?',
        'faq3A': 'Create a free account, go to "List Your Place", fill in details about your accommodation or job opportunity, and publish. Lister plan unlocks unlimited listings.',
        'faq4Q': 'Are there any booking fees?',
        'faq4A': 'No booking fees! We only charge subscription fees. Connect directly with hosts or employers without hidden transaction costs.',
        'faq5Q': 'How does messaging work?',
        'faq5A': 'Phone-verified users can send unlimited messages. Conversations are private and secure. We never share your contact details without permission.',
        'faq6Q': 'What if I have a dispute?',
        'faq6A': 'Both parties can access our mediation service. Agreements are stored on the platform. We review evidence and help find fair resolutions.',
        'faq7Q': 'Can I cancel my subscription anytime?',
        'faq7A': 'Yes! Cancel anytime from your profile settings. You keep access until the end of your billing period. No cancellation fees.',
        'faq8Q': 'Do you support multiple languages?',
        'faq8A': 'Yes! Our platform supports English, German, Spanish, French, Italian, and Portuguese. Switch languages from the top menu.',
        'faqContactText': 'Still have questions? Our support team is here to help.',
        'faqContactBtn': 'Contact Support',
        
        # TrustAndSafety Component (14 keys)
        'trustSectionTitle': 'Built on Trust & Safety',
        'trustSectionDesc': 'Multiple verification layers and transparent ratings help you connect with confidence',
        'trustEmailVerifyTitle': 'Email Verification',
        'trustEmailVerifyDesc': 'Required for all accounts. Confirms your identity and enables platform access.',
        'trustPhoneVerifyTitle': 'Phone Verification',
        'trustPhoneVerifyDesc': 'Unlock messaging and build trust. Quick SMS verification process.',
        'trustIDVerifyTitle': 'ID Verification',
        'trustIDVerifyDesc': 'Optional premium verification. Dramatically increases trust scores and visibility.',
        'trustScoresTitle': 'Trust Scores',
        'trustScoresDesc': 'Transparent ratings from previous hosts and guests. Build your reputation over time.',
        'trustAgreementsTitle': 'Smart Agreements',
        'trustAgreementsDesc': 'Digital contracts in plain language. Both parties sign before arrival.',
        'trustDisputeTitle': 'Dispute Resolution',
        'trustDisputeDesc': 'Fair mediation service. We review evidence and help resolve conflicts.',
        'learnAgreementsBtn': 'Learn About Agreements',
        'avgTrustScore': 'Average Trust Score',
        'avgTrustScoreDesc': 'Based on verified users',
        'idVerified': 'ID Verified',
        
        # SubscriptionTiers Component (21 keys)
        'pricingSectionTitle': 'Choose Your Plan',
        'pricingSectionDesc': 'Start free forever or unlock premium features with our paid plans',
        'planFreeName': 'Free',
        'planFreeBtn': 'Get Started Free',
        'planFreeFeat1': 'Browse unlimited listings',
        'planFreeFeat2': 'Email & phone verification',
        'planFreeFeat3': 'Basic profile',
        'planFreeFeat4': 'View contact details',
        'planFreeFeat5': 'Community forum access',
        'planSearcherName': 'Searcher',
        'planSearcherBtn': 'Start Free Trial',
        'planSearcherFeat1': 'Everything in Free',
        'planSearcherFeat2': 'Unlimited messaging',
        'planSearcherFeat3': 'Advanced search filters',
        'planSearcherFeat4': 'Saved searches & alerts',
        'planSearcherFeat5': 'Priority support',
        'planSearcherFeat6': 'No ads',
        'planListerName': 'Lister',
        'planListerBtn': 'Start Free Trial',
        'planListerFeat1': 'Everything in Searcher',
        'planListerFeat2': 'Unlimited listings',
        'planListerFeat3': 'Featured placement',
        'planListerFeat4': 'Analytics dashboard',
        'planListerFeat5': 'Bulk edit tools',
        'planListerFeat6': 'Calendar integration',
        'planListerFeat7': 'Dedicated account manager',
        'premiumIDTitle': 'Premium ID Verification',
        'premiumIDDesc': 'Want to stand out? Add government ID verification to dramatically increase your trust score and get priority visibility in search results.',
        'premiumIDEarlyBird': 'Early Bird Special: First 1,000 users get lifetime free ID verification!',
        'mostPopular': 'Most Popular',
        
        # HeroWithCTA Component (7 keys)
        'ctaHeroTitle': 'Ready to Find Your Next Adventure?',
        'ctaHeroDesc': 'Join thousands of travelers and hosts connecting through meaningful seasonal experiences',
        'ctaGetStartedBtn': 'Get Started Free',
        'ctaLearnMoreBtn': 'Learn More',
        'ctaBadgeVerified': 'Verified Members',
        'ctaBadgeSafe': 'Safe & Secure',
        'ctaBadgeProtected': 'Protected Agreements',
        
        # FeatureHighlights Component (3 keys)
        'featureSectionTitle': 'How Seasoners Works',
        'featureSectionDesc': 'Connecting travelers and hosts through trust and transparency',
        'howItWorksDesc': 'Simple steps to get started',
    },
    'de': {
        # FAQ (German)
        'faqSectionTitle': 'Häufig gestellte Fragen',
        'faqSectionDesc': 'Alles, was Sie über saisonale Arbeit und Aufenthalte wissen müssen',
        'faq1Q': 'Wie funktioniert die 90-tägige kostenlose Testversion?',
        'faq1A': 'Melden Sie sich für einen kostenpflichtigen Plan an und hinterlegen Sie Ihre Zahlungsdaten. Sie erhalten 90 Tage lang vollen Zugang komplett kostenlos. Jederzeit vor Ende der Testphase kündbar ohne Kosten.',
        'faq2Q': 'Welche Verifizierungsstufen benötige ich?',
        'faq2A': 'Basis-Nutzer (kostenlos) benötigen eine E-Mail-Verifizierung. Kostenpflichtige Pläne erfordern Telefonverifizierung für Nachrichten. ID-Verifizierung ist optional, schafft aber Vertrauen.',
        'faq3Q': 'Wie liste ich meine Unterkunft oder meinen Job?',
        'faq3A': 'Erstellen Sie ein kostenloses Konto, gehen Sie zu "Unterkunft eintragen", füllen Sie die Details aus und veröffentlichen Sie. Der Lister-Plan ermöglicht unbegrenzte Einträge.',
        'faq4Q': 'Gibt es Buchungsgebühren?',
        'faq4A': 'Keine Buchungsgebühren! Wir erheben nur Abonnementgebühren. Verbinden Sie sich direkt mit Gastgebern ohne versteckte Kosten.',
        'faq5Q': 'Wie funktioniert das Messaging?',
        'faq5A': 'Telefonverifizierte Nutzer können unbegrenzt Nachrichten senden. Gespräche sind privat und sicher.',
        'faq6Q': 'Was passiert bei einem Streitfall?',
        'faq6A': 'Beide Parteien können unseren Mediationsservice nutzen. Wir prüfen Beweise und helfen bei fairen Lösungen.',
        'faq7Q': 'Kann ich mein Abonnement jederzeit kündigen?',
        'faq7A': 'Ja! Jederzeit in den Profileinstellungen kündbar. Sie behalten Zugang bis zum Ende der Abrechnungsperiode.',
        'faq8Q': 'Unterstützen Sie mehrere Sprachen?',
        'faq8A': 'Ja! Unsere Plattform unterstützt Englisch, Deutsch, Spanisch, Französisch, Italienisch und Portugiesisch.',
        'faqContactText': 'Haben Sie noch Fragen? Unser Support-Team hilft Ihnen gerne.',
        'faqContactBtn': 'Support kontaktieren',
        'trustSectionTitle': 'Aufgebaut auf Vertrauen & Sicherheit',
        'trustSectionDesc': 'Mehrere Verifizierungsebenen und transparente Bewertungen helfen Ihnen, sich sicher zu verbinden',
        'trustEmailVerifyTitle': 'E-Mail-Verifizierung',
        'trustEmailVerifyDesc': 'Erforderlich für alle Konten. Bestätigt Ihre Identität.',
        'trustPhoneVerifyTitle': 'Telefonverifizierung',
        'trustPhoneVerifyDesc': 'Schaltet Messaging frei. Schneller SMS-Verifizierungsprozess.',
        'trustIDVerifyTitle': 'ID-Verifizierung',
        'trustIDVerifyDesc': 'Optionale Premium-Verifizierung. Erhöht Vertrauenswerte dramatisch.',
        'trustScoresTitle': 'Vertrauenswerte',
        'trustScoresDesc': 'Transparente Bewertungen von früheren Gastgebern und Gästen.',
        'trustAgreementsTitle': 'Intelligente Vereinbarungen',
        'trustAgreementsDesc': 'Digitale Verträge in einfacher Sprache.',
        'trustDisputeTitle': 'Streitbeilegung',
        'trustDisputeDesc': 'Fairer Mediationsservice zur Konfliktlösung.',
        'learnAgreementsBtn': 'Mehr über Vereinbarungen',
        'avgTrustScore': 'Durchschnittlicher Vertrauenswert',
        'avgTrustScoreDesc': 'Basierend auf verifizierten Nutzern',
        'idVerified': 'ID verifiziert',
        'pricingSectionTitle': 'Wählen Sie Ihren Plan',
        'pricingSectionDesc': 'Starten Sie kostenlos oder schalten Sie Premium-Funktionen frei',
        'planFreeName': 'Kostenlos',
        'planFreeBtn': 'Kostenlos starten',
        'planFreeFeat1': 'Unbegrenzt Angebote durchsuchen',
        'planFreeFeat2': 'E-Mail & Telefonverifizierung',
        'planFreeFeat3': 'Basisprofil',
        'planFreeFeat4': 'Kontaktdaten einsehen',
        'planFreeFeat5': 'Community-Forum Zugang',
        'planSearcherName': 'Sucher',
        'planSearcherBtn': 'Kostenlose Testversion starten',
        'planSearcherFeat1': 'Alles in Kostenlos',
        'planSearcherFeat2': 'Unbegrenzte Nachrichten',
        'planSearcherFeat3': 'Erweiterte Suchfilter',
        'planSearcherFeat4': 'Gespeicherte Suchen & Benachrichtigungen',
        'planSearcherFeat5': 'Prioritätssupport',
        'planSearcherFeat6': 'Keine Werbung',
        'planListerName': 'Vermieter',
        'planListerBtn': 'Kostenlose Testversion starten',
        'planListerFeat1': 'Alles in Sucher',
        'planListerFeat2': 'Unbegrenzte Einträge',
        'planListerFeat3': 'Hervorgehobene Platzierung',
        'planListerFeat4': 'Analyse-Dashboard',
        'planListerFeat5': 'Massenbearbeitungswerkzeuge',
        'planListerFeat6': 'Kalenderintegration',
        'planListerFeat7': 'Dedizierter Account-Manager',
        'premiumIDTitle': 'Premium-ID-Verifizierung',
        'premiumIDDesc': 'Möchten Sie sich abheben? Fügen Sie eine behördliche ID-Verifizierung hinzu, um Ihren Vertrauenswert zu erhöhen.',
        'premiumIDEarlyBird': 'Early Bird Spezial: Die ersten 1.000 Nutzer erhalten lebenslang kostenlose ID-Verifizierung!',
        'mostPopular': 'Am beliebtesten',
        'ctaHeroTitle': 'Bereit für Ihr nächstes Abenteuer?',
        'ctaHeroDesc': 'Schließen Sie sich Tausenden von Reisenden und Gastgebern an',
        'ctaGetStartedBtn': 'Kostenlos starten',
        'ctaLearnMoreBtn': 'Mehr erfahren',
        'ctaBadgeVerified': 'Verifizierte Mitglieder',
        'ctaBadgeSafe': 'Sicher & Geschützt',
        'ctaBadgeProtected': 'Geschützte Vereinbarungen',
        'featureSectionTitle': 'Wie Seasoners funktioniert',
        'featureSectionDesc': 'Reisende und Gastgeber durch Vertrauen verbinden',
        'howItWorksDesc': 'Einfache Schritte zum Einstieg',
    },
    # I'll add ES, FR, IT, PT in the same comprehensive way
}

# Add Spanish, French, Italian, Portuguese translations
ALL_KEYS['es'] = {
    'faqSectionTitle': 'Preguntas frecuentes',
    'faqSectionDesc': 'Todo lo que necesitas saber sobre trabajo y estadías estacionales',
    'faq1Q': '¿Cómo funciona la prueba gratuita de 90 días?',
    'faq1A': 'Regístrate en cualquier plan de pago y agrega tus detalles de pago. Obtienes acceso completo durante 90 días completamente gratis. Cancela en cualquier momento antes de que termine la prueba sin cargos.',
    'faq2Q': '¿Qué niveles de verificación necesito?',
    'faq2A': 'Los usuarios básicos (gratuitos) necesitan verificación de correo electrónico. Los planes de pago requieren verificación telefónica para mensajes. La verificación de ID es opcional pero genera confianza.',
    'faq3Q': '¿Cómo publico mi propiedad o trabajo?',
    'faq3A': 'Crea una cuenta gratuita, ve a "Publica tu propiedad", completa los detalles y publica. El plan Lister desbloquea anuncios ilimitados.',
    'faq4Q': '¿Hay tarifas de reserva?',
    'faq4A': '¡Sin tarifas de reserva! Solo cobramos tarifas de suscripción. Conéctate directamente sin costos ocultos.',
    'faq5Q': '¿Cómo funcionan los mensajes?',
    'faq5A': 'Los usuarios verificados por teléfono pueden enviar mensajes ilimitados. Las conversaciones son privadas y seguras.',
    'faq6Q': '¿Qué pasa si tengo una disputa?',
    'faq6A': 'Ambas partes pueden acceder a nuestro servicio de mediación. Revisamos evidencia y ayudamos a encontrar resoluciones justas.',
    'faq7Q': '¿Puedo cancelar mi suscripción en cualquier momento?',
    'faq7A': 'Sí! Cancela en cualquier momento desde tu configuración de perfil. Mantienes acceso hasta el final del período de facturación.',
    'faq8Q': '¿Admiten varios idiomas?',
    'faq8A': 'Sí! Nuestra plataforma admite inglés, alemán, español, francés, italiano y portugués.',
    'faqContactText': '¿Aún tienes preguntas? Nuestro equipo de soporte está aquí para ayudar.',
    'faqContactBtn': 'Contactar soporte',
    'trustSectionTitle': 'Construido sobre confianza y seguridad',
    'trustSectionDesc': 'Múltiples capas de verificación y calificaciones transparentes te ayudan a conectar con confianza',
    'trustEmailVerifyTitle': 'Verificación de correo',
    'trustEmailVerifyDesc': 'Requerida para todas las cuentas. Confirma tu identidad.',
    'trustPhoneVerifyTitle': 'Verificación telefónica',
    'trustPhoneVerifyDesc': 'Desbloquea mensajes. Proceso rápido de verificación por SMS.',
    'trustIDVerifyTitle': 'Verificación de ID',
    'trustIDVerifyDesc': 'Verificación premium opcional. Aumenta dramáticamente las puntuaciones de confianza.',
    'trustScoresTitle': 'Puntuaciones de confianza',
    'trustScoresDesc': 'Calificaciones transparentes de anfitriones y huéspedes anteriores.',
    'trustAgreementsTitle': 'Acuerdos inteligentes',
    'trustAgreementsDesc': 'Contratos digitales en lenguaje claro.',
    'trustDisputeTitle': 'Resolución de disputas',
    'trustDisputeDesc': 'Servicio de mediación justa para resolver conflictos.',
    'learnAgreementsBtn': 'Más sobre acuerdos',
    'avgTrustScore': 'Puntuación promedio de confianza',
    'avgTrustScoreDesc': 'Basado en usuarios verificados',
    'idVerified': 'ID verificado',
    'pricingSectionTitle': 'Elige tu plan',
    'pricingSectionDesc': 'Comienza gratis para siempre o desbloquea funciones premium',
    'planFreeName': 'Gratis',
    'planFreeBtn': 'Comenzar gratis',
    'planFreeFeat1': 'Explorar anuncios ilimitados',
    'planFreeFeat2': 'Verificación de correo y teléfono',
    'planFreeFeat3': 'Perfil básico',
    'planFreeFeat4': 'Ver detalles de contacto',
    'planFreeFeat5': 'Acceso al foro comunitario',
    'planSearcherName': 'Buscador',
    'planSearcherBtn': 'Iniciar prueba gratuita',
    'planSearcherFeat1': 'Todo en Gratis',
    'planSearcherFeat2': 'Mensajes ilimitados',
    'planSearcherFeat3': 'Filtros de búsqueda avanzados',
    'planSearcherFeat4': 'Búsquedas guardadas y alertas',
    'planSearcherFeat5': 'Soporte prioritario',
    'planSearcherFeat6': 'Sin anuncios',
    'planListerName': 'Anunciante',
    'planListerBtn': 'Iniciar prueba gratuita',
    'planListerFeat1': 'Todo en Buscador',
    'planListerFeat2': 'Anuncios ilimitados',
    'planListerFeat3': 'Colocación destacada',
    'planListerFeat4': 'Panel de análisis',
    'planListerFeat5': 'Herramientas de edición masiva',
    'planListerFeat6': 'Integración de calendario',
    'planListerFeat7': 'Gerente de cuenta dedicado',
    'premiumIDTitle': 'Verificación premium de ID',
    'premiumIDDesc': '¿Quieres destacar? Agrega verificación de ID gubernamental para aumentar tu puntuación de confianza.',
    'premiumIDEarlyBird': 'Oferta especial: ¡Los primeros 1.000 usuarios obtienen verificación de ID gratis de por vida!',
    'mostPopular': 'Más popular',
    'ctaHeroTitle': '¿Listo para encontrar tu próxima aventura?',
    'ctaHeroDesc': 'Únete a miles de viajeros y anfitriones conectando a través de experiencias estacionales significativas',
    'ctaGetStartedBtn': 'Comenzar gratis',
    'ctaLearnMoreBtn': 'Más información',
    'ctaBadgeVerified': 'Miembros verificados',
    'ctaBadgeSafe': 'Seguro y protegido',
    'ctaBadgeProtected': 'Acuerdos protegidos',
    'featureSectionTitle': 'Cómo funciona Seasoners',
    'featureSectionDesc': 'Conectando viajeros y anfitriones a través de confianza y transparencia',
    'howItWorksDesc': 'Pasos simples para comenzar',
}

ALL_KEYS['fr'] = {
    'faqSectionTitle': 'Questions fréquemment posées',
    'faqSectionDesc': 'Tout ce que vous devez savoir sur le travail et les séjours saisonniers',
    'faq1Q': 'Comment fonctionne l\'essai gratuit de 90 jours?',
    'faq1A': 'Inscrivez-vous à n\'importe quel plan payant et ajoutez vos détails de paiement. Vous obtenez un accès complet pendant 90 jours gratuitement. Annulez à tout moment avant la fin de l\'essai sans frais.',
    'faq2Q': 'Quels niveaux de vérification ai-je besoin?',
    'faq2A': 'Les utilisateurs de base (gratuits) ont besoin d\'une vérification par e-mail. Les plans payants nécessitent une vérification téléphonique pour la messagerie. La vérification d\'identité est optionnelle mais renforce la confiance.',
    'faq3Q': 'Comment puis-je lister ma propriété ou mon emploi?',
    'faq3A': 'Créez un compte gratuit, allez dans "Listez votre propriété", remplissez les détails et publiez. Le plan Lister débloque les annonces illimitées.',
    'faq4Q': 'Y a-t-il des frais de réservation?',
    'faq4A': 'Pas de frais de réservation! Nous facturons uniquement des frais d\'abonnement. Connectez-vous directement sans coûts cachés.',
    'faq5Q': 'Comment fonctionne la messagerie?',
    'faq5A': 'Les utilisateurs vérifiés par téléphone peuvent envoyer des messages illimités. Les conversations sont privées et sécurisées.',
    'faq6Q': 'Que se passe-t-il si j\'ai un différend?',
    'faq6A': 'Les deux parties peuvent accéder à notre service de médiation. Nous examinons les preuves et aidons à trouver des résolutions équitables.',
    'faq7Q': 'Puis-je annuler mon abonnement à tout moment?',
    'faq7A': 'Oui! Annulez à tout moment depuis vos paramètres de profil. Vous conservez l\'accès jusqu\'à la fin de votre période de facturation.',
    'faq8Q': 'Supportez-vous plusieurs langues?',
    'faq8A': 'Oui! Notre plateforme prend en charge l\'anglais, l\'allemand, l\'espagnol, le français, l\'italien et le portugais.',
    'faqContactText': 'Vous avez encore des questions? Notre équipe de support est là pour vous aider.',
    'faqContactBtn': 'Contacter le support',
    'trustSectionTitle': 'Construit sur la confiance et la sécurité',
    'trustSectionDesc': 'Plusieurs niveaux de vérification et des évaluations transparentes vous aident à vous connecter en toute confiance',
    'trustEmailVerifyTitle': 'Vérification par e-mail',
    'trustEmailVerifyDesc': 'Requis pour tous les comptes. Confirme votre identité.',
    'trustPhoneVerifyTitle': 'Vérification téléphonique',
    'trustPhoneVerifyDesc': 'Débloque la messagerie. Processus de vérification SMS rapide.',
    'trustIDVerifyTitle': 'Vérification d\'identité',
    'trustIDVerifyDesc': 'Vérification premium optionnelle. Augmente considérablement les scores de confiance.',
    'trustScoresTitle': 'Scores de confiance',
    'trustScoresDesc': 'Évaluations transparentes des hôtes et invités précédents.',
    'trustAgreementsTitle': 'Accords intelligents',
    'trustAgreementsDesc': 'Contrats numériques en langage clair.',
    'trustDisputeTitle': 'Résolution des différends',
    'trustDisputeDesc': 'Service de médiation équitable pour résoudre les conflits.',
    'learnAgreementsBtn': 'En savoir plus sur les accords',
    'avgTrustScore': 'Score de confiance moyen',
    'avgTrustScoreDesc': 'Basé sur les utilisateurs vérifiés',
    'idVerified': 'ID vérifié',
    'pricingSectionTitle': 'Choisissez votre plan',
    'pricingSectionDesc': 'Commencez gratuitement pour toujours ou débloquez des fonctionnalités premium',
    'planFreeName': 'Gratuit',
    'planFreeBtn': 'Commencer gratuitement',
    'planFreeFeat1': 'Parcourir les annonces illimitées',
    'planFreeFeat2': 'Vérification par e-mail et téléphone',
    'planFreeFeat3': 'Profil de base',
    'planFreeFeat4': 'Voir les coordonnées',
    'planFreeFeat5': 'Accès au forum communautaire',
    'planSearcherName': 'Chercheur',
    'planSearcherBtn': 'Commencer l\'essai gratuit',
    'planSearcherFeat1': 'Tout dans Gratuit',
    'planSearcherFeat2': 'Messages illimités',
    'planSearcherFeat3': 'Filtres de recherche avancés',
    'planSearcherFeat4': 'Recherches sauvegardées et alertes',
    'planSearcherFeat5': 'Support prioritaire',
    'planSearcherFeat6': 'Sans publicité',
    'planListerName': 'Annonceur',
    'planListerBtn': 'Commencer l\'essai gratuit',
    'planListerFeat1': 'Tout dans Chercheur',
    'planListerFeat2': 'Annonces illimitées',
    'planListerFeat3': 'Placement en vedette',
    'planListerFeat4': 'Tableau de bord analytique',
    'planListerFeat5': 'Outils d\'édition en masse',
    'planListerFeat6': 'Intégration du calendrier',
    'planListerFeat7': 'Gestionnaire de compte dédié',
    'premiumIDTitle': 'Vérification d\'identité premium',
    'premiumIDDesc': 'Vous voulez vous démarquer? Ajoutez une vérification d\'identité gouvernementale pour augmenter votre score de confiance.',
    'premiumIDEarlyBird': 'Offre spéciale: Les 1 000 premiers utilisateurs obtiennent une vérification d\'identité gratuite à vie!',
    'mostPopular': 'Le plus populaire',
    'ctaHeroTitle': 'Prêt à trouver votre prochaine aventure?',
    'ctaHeroDesc': 'Rejoignez des milliers de voyageurs et d\'hôtes se connectant à travers des expériences saisonnières significatives',
    'ctaGetStartedBtn': 'Commencer gratuitement',
    'ctaLearnMoreBtn': 'En savoir plus',
    'ctaBadgeVerified': 'Membres vérifiés',
    'ctaBadgeSafe': 'Sûr et sécurisé',
    'ctaBadgeProtected': 'Accords protégés',
    'featureSectionTitle': 'Comment fonctionne Seasoners',
    'featureSectionDesc': 'Connecter les voyageurs et les hôtes par la confiance et la transparence',
    'howItWorksDesc': 'Étapes simples pour commencer',
}

ALL_KEYS['it'] = {
    'faqSectionTitle': 'Domande frequenti',
    'faqSectionDesc': 'Tutto quello che devi sapere su lavoro e soggiorni stagionali',
    'faq1Q': 'Come funziona la prova gratuita di 90 giorni?',
    'faq1A': 'Registrati per qualsiasi piano a pagamento e aggiungi i tuoi dettagli di pagamento. Ottieni accesso completo per 90 giorni completamente gratis. Annulla in qualsiasi momento prima della fine della prova senza costi.',
    'faq2Q': 'Quali livelli di verifica mi servono?',
    'faq2A': 'Gli utenti base (gratuiti) necessitano di verifica email. I piani a pagamento richiedono verifica telefonica per i messaggi. La verifica ID è opzionale ma aumenta la fiducia.',
    'faq3Q': 'Come pubblico la mia proprietà o lavoro?',
    'faq3A': 'Crea un account gratuito, vai su "Elenca la tua proprietà", compila i dettagli e pubblica. Il piano Lister sblocca annunci illimitati.',
    'faq4Q': 'Ci sono commissioni di prenotazione?',
    'faq4A': 'Nessuna commissione di prenotazione! Addebitiamo solo commissioni di abbonamento. Connettiti direttamente senza costi nascosti.',
    'faq5Q': 'Come funziona la messaggistica?',
    'faq5A': 'Gli utenti verificati telefonicamente possono inviare messaggi illimitati. Le conversazioni sono private e sicure.',
    'faq6Q': 'Cosa succede se ho una disputa?',
    'faq6A': 'Entrambe le parti possono accedere al nostro servizio di mediazione. Esaminiamo le prove e aiutiamo a trovare risoluzioni eque.',
    'faq7Q': 'Posso cancellare il mio abbonamento in qualsiasi momento?',
    'faq7A': 'Sì! Annulla in qualsiasi momento dalle impostazioni del profilo. Mantieni l\'accesso fino alla fine del periodo di fatturazione.',
    'faq8Q': 'Supportate più lingue?',
    'faq8A': 'Sì! La nostra piattaforma supporta inglese, tedesco, spagnolo, francese, italiano e portoghese.',
    'faqContactText': 'Hai ancora domande? Il nostro team di supporto è qui per aiutarti.',
    'faqContactBtn': 'Contatta il supporto',
    'trustSectionTitle': 'Costruito sulla fiducia e sicurezza',
    'trustSectionDesc': 'Più livelli di verifica e valutazioni trasparenti ti aiutano a connetterti con fiducia',
    'trustEmailVerifyTitle': 'Verifica email',
    'trustEmailVerifyDesc': 'Richiesta per tutti gli account. Conferma la tua identità.',
    'trustPhoneVerifyTitle': 'Verifica telefonica',
    'trustPhoneVerifyDesc': 'Sblocca i messaggi. Processo di verifica SMS rapido.',
    'trustIDVerifyTitle': 'Verifica ID',
    'trustIDVerifyDesc': 'Verifica premium opzionale. Aumenta drammaticamente i punteggi di fiducia.',
    'trustScoresTitle': 'Punteggi di fiducia',
    'trustScoresDesc': 'Valutazioni trasparenti da host e ospiti precedenti.',
    'trustAgreementsTitle': 'Accordi intelligenti',
    'trustAgreementsDesc': 'Contratti digitali in linguaggio chiaro.',
    'trustDisputeTitle': 'Risoluzione delle dispute',
    'trustDisputeDesc': 'Servizio di mediazione equo per risolvere i conflitti.',
    'learnAgreementsBtn': 'Scopri gli accordi',
    'avgTrustScore': 'Punteggio di fiducia medio',
    'avgTrustScoreDesc': 'Basato su utenti verificati',
    'idVerified': 'ID verificato',
    'pricingSectionTitle': 'Scegli il tuo piano',
    'pricingSectionDesc': 'Inizia gratuitamente per sempre o sblocca funzionalità premium',
    'planFreeName': 'Gratuito',
    'planFreeBtn': 'Inizia gratis',
    'planFreeFeat1': 'Sfoglia annunci illimitati',
    'planFreeFeat2': 'Verifica email e telefono',
    'planFreeFeat3': 'Profilo base',
    'planFreeFeat4': 'Visualizza dettagli di contatto',
    'planFreeFeat5': 'Accesso al forum della comunità',
    'planSearcherName': 'Cercatore',
    'planSearcherBtn': 'Inizia prova gratuita',
    'planSearcherFeat1': 'Tutto in Gratuito',
    'planSearcherFeat2': 'Messaggi illimitati',
    'planSearcherFeat3': 'Filtri di ricerca avanzati',
    'planSearcherFeat4': 'Ricerche salvate e avvisi',
    'planSearcherFeat5': 'Supporto prioritario',
    'planSearcherFeat6': 'Nessuna pubblicità',
    'planListerName': 'Inserzionista',
    'planListerBtn': 'Inizia prova gratuita',
    'planListerFeat1': 'Tutto in Cercatore',
    'planListerFeat2': 'Annunci illimitati',
    'planListerFeat3': 'Posizionamento in evidenza',
    'planListerFeat4': 'Dashboard analitica',
    'planListerFeat5': 'Strumenti di modifica in blocco',
    'planListerFeat6': 'Integrazione calendario',
    'planListerFeat7': 'Account manager dedicato',
    'premiumIDTitle': 'Verifica ID premium',
    'premiumIDDesc': 'Vuoi distinguerti? Aggiungi la verifica ID governativa per aumentare il tuo punteggio di fiducia.',
    'premiumIDEarlyBird': 'Offerta speciale: I primi 1.000 utenti ottengono verifica ID gratuita a vita!',
    'mostPopular': 'Più popolare',
    'ctaHeroTitle': 'Pronto a trovare la tua prossima avventura?',
    'ctaHeroDesc': 'Unisciti a migliaia di viaggiatori e host connettendoti attraverso esperienze stagionali significative',
    'ctaGetStartedBtn': 'Inizia gratis',
    'ctaLearnMoreBtn': 'Scopri di più',
    'ctaBadgeVerified': 'Membri verificati',
    'ctaBadgeSafe': 'Sicuro e protetto',
    'ctaBadgeProtected': 'Accordi protetti',
    'featureSectionTitle': 'Come funziona Seasoners',
    'featureSectionDesc': 'Connettere viaggiatori e host attraverso fiducia e trasparenza',
    'howItWorksDesc': 'Passaggi semplici per iniziare',
}

ALL_KEYS['pt'] = {
    'faqSectionTitle': 'Perguntas frequentes',
    'faqSectionDesc': 'Tudo o que você precisa saber sobre trabalho e estadias sazonais',
    'faq1Q': 'Como funciona o teste grátis de 90 dias?',
    'faq1A': 'Inscreva-se em qualquer plano pago e adicione seus detalhes de pagamento. Você obtém acesso completo por 90 dias completamente grátis. Cancele a qualquer momento antes do final do teste sem cobranças.',
    'faq2Q': 'Quais níveis de verificação eu preciso?',
    'faq2A': 'Usuários básicos (gratuitos) precisam de verificação de e-mail. Planos pagos exigem verificação telefônica para mensagens. A verificação de ID é opcional mas gera confiança.',
    'faq3Q': 'Como publico minha propriedade ou trabalho?',
    'faq3A': 'Crie uma conta gratuita, vá em "Liste sua propriedade", preencha os detalhes e publique. O plano Lister desbloqueia anúncios ilimitados.',
    'faq4Q': 'Há taxas de reserva?',
    'faq4A': 'Sem taxas de reserva! Cobramos apenas taxas de assinatura. Conecte-se diretamente sem custos ocultos.',
    'faq5Q': 'Como funciona o sistema de mensagens?',
    'faq5A': 'Usuários verificados por telefone podem enviar mensagens ilimitadas. As conversas são privadas e seguras.',
    'faq6Q': 'E se eu tiver uma disputa?',
    'faq6A': 'Ambas as partes podem acessar nosso serviço de mediação. Revisamos evidências e ajudamos a encontrar resoluções justas.',
    'faq7Q': 'Posso cancelar minha assinatura a qualquer momento?',
    'faq7A': 'Sim! Cancele a qualquer momento nas configurações do perfil. Você mantém o acesso até o final do período de cobrança.',
    'faq8Q': 'Vocês suportam vários idiomas?',
    'faq8A': 'Sim! Nossa plataforma suporta inglês, alemão, espanhol, francês, italiano e português.',
    'faqContactText': 'Ainda tem dúvidas? Nossa equipe de suporte está aqui para ajudar.',
    'faqContactBtn': 'Contatar suporte',
    'trustSectionTitle': 'Construído sobre confiança e segurança',
    'trustSectionDesc': 'Múltiplas camadas de verificação e avaliações transparentes ajudam você a se conectar com confiança',
    'trustEmailVerifyTitle': 'Verificação de e-mail',
    'trustEmailVerifyDesc': 'Necessária para todas as contas. Confirma sua identidade.',
    'trustPhoneVerifyTitle': 'Verificação telefônica',
    'trustPhoneVerifyDesc': 'Desbloqueia mensagens. Processo rápido de verificação por SMS.',
    'trustIDVerifyTitle': 'Verificação de ID',
    'trustIDVerifyDesc': 'Verificação premium opcional. Aumenta dramaticamente as pontuações de confiança.',
    'trustScoresTitle': 'Pontuações de confiança',
    'trustScoresDesc': 'Avaliações transparentes de anfitriões e hóspedes anteriores.',
    'trustAgreementsTitle': 'Acordos inteligentes',
    'trustAgreementsDesc': 'Contratos digitais em linguagem clara.',
    'trustDisputeTitle': 'Resolução de disputas',
    'trustDisputeDesc': 'Serviço de mediação justa para resolver conflitos.',
    'learnAgreementsBtn': 'Saiba mais sobre acordos',
    'avgTrustScore': 'Pontuação média de confiança',
    'avgTrustScoreDesc': 'Baseado em usuários verificados',
    'idVerified': 'ID verificado',
    'pricingSectionTitle': 'Escolha seu plano',
    'pricingSectionDesc': 'Comece grátis para sempre ou desbloqueie recursos premium',
    'planFreeName': 'Grátis',
    'planFreeBtn': 'Começar grátis',
    'planFreeFeat1': 'Navegar anúncios ilimitados',
    'planFreeFeat2': 'Verificação de e-mail e telefone',
    'planFreeFeat3': 'Perfil básico',
    'planFreeFeat4': 'Ver detalhes de contato',
    'planFreeFeat5': 'Acesso ao fórum da comunidade',
    'planSearcherName': 'Buscador',
    'planSearcherBtn': 'Iniciar teste grátis',
    'planSearcherFeat1': 'Tudo em Grátis',
    'planSearcherFeat2': 'Mensagens ilimitadas',
    'planSearcherFeat3': 'Filtros de pesquisa avançados',
    'planSearcherFeat4': 'Pesquisas salvas e alertas',
    'planSearcherFeat5': 'Suporte prioritário',
    'planSearcherFeat6': 'Sem anúncios',
    'planListerName': 'Anunciante',
    'planListerBtn': 'Iniciar teste grátis',
    'planListerFeat1': 'Tudo em Buscador',
    'planListerFeat2': 'Anúncios ilimitados',
    'planListerFeat3': 'Posicionamento em destaque',
    'planListerFeat4': 'Painel de análise',
    'planListerFeat5': 'Ferramentas de edição em massa',
    'planListerFeat6': 'Integração de calendário',
    'planListerFeat7': 'Gerente de conta dedicado',
    'premiumIDTitle': 'Verificação de ID premium',
    'premiumIDDesc': 'Quer se destacar? Adicione verificação de ID governamental para aumentar sua pontuação de confiança.',
    'premiumIDEarlyBird': 'Oferta especial: Os primeiros 1.000 usuários obtêm verificação de ID grátis vitalícia!',
    'mostPopular': 'Mais popular',
    'ctaHeroTitle': 'Pronto para encontrar sua próxima aventura?',
    'ctaHeroDesc': 'Junte-se a milhares de viajantes e anfitriões se conectando através de experiências sazonais significativas',
    'ctaGetStartedBtn': 'Começar grátis',
    'ctaLearnMoreBtn': 'Saiba mais',
    'ctaBadgeVerified': 'Membros verificados',
    'ctaBadgeSafe': 'Seguro e protegido',
    'ctaBadgeProtected': 'Acordos protegidos',
    'featureSectionTitle': 'Como funciona o Seasoners',
    'featureSectionDesc': 'Conectando viajantes e anfitriões através de confiança e transparência',
    'howItWorksDesc': 'Passos simples para começar',
}

def add_keys_to_locale(locale_code, new_keys):
    """Add missing keys to a locale file."""
    file_path = f'locales/{locale_code}.json'
    
    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            data = json.load(f)
        
        added_count = 0
        for key, value in new_keys.items():
            if key not in data:
                data[key] = value
                added_count += 1
        
        # Sort keys alphabetically
        sorted_data = dict(sorted(data.items()))
        
        with open(file_path, 'w', encoding='utf-8') as f:
            json.dump(sorted_data, f, ensure_ascii=False, indent=2)
        
        print(f"✓ {locale_code}.json: Added {added_count} keys (Total: {len(sorted_data)})")
        return added_count
    except Exception as e:
        print(f"✗ Error with {locale_code}.json: {e}")
        return 0

print("=" * 60)
print("COMPREHENSIVE TRANSLATION KEY ADDITION")
print("=" * 60)
print()

total_added = 0
for locale in ['en', 'de', 'es', 'fr', 'it', 'pt']:
    added = add_keys_to_locale(locale, ALL_KEYS[locale])
    total_added += added

print()
print("=" * 60)
print(f"✓ COMPLETE! Added {total_added} total keys across all locales")
print("=" * 60)
