import json

locales = ['en', 'de', 'es', 'fr', 'it', 'pt']
data = {}
for locale in locales:
    with open(f'locales/{locale}.json', 'r', encoding='utf-8') as f:
        data[locale] = json.load(f)

new_keys = {
    'en': {
        'socialProofTitle': 'Trusted by Global Seasonal Workers & Hosts',
        'socialProofDesc': 'Verified members across 50+ countries creating meaningful work and living experiences.',
        'verifiedMembers': 'Verified Members',
        'verifiedListings': 'Verified Listings',
        'successfulMatches': 'Successful Matches',
        'countriesActive': 'Countries Active',
        'featureVerifiedUsersTitle': 'Verified Users',
        'featureVerifiedUsersDesc': 'Every user is verified through email, phone, and optional ID.',
        'featureReputationTitle': 'Verified Reputation',
        'featureReputationDesc': 'Every interaction builds reputation. Users with excellent ratings stand out.',
        'featureAgreementsTitle': 'Legally Clear Agreements',
        'featureAgreementsDesc': 'Dual-language agreements with digital signatures protect both parties.',
        'featureCommunicationTitle': 'Global Communication',
        'featureCommunicationDesc': 'Connect worldwide. Real-time translation removes language barriers.',
        'featureMessagingTitle': 'Private & Secure Messaging',
        'featureMessagingDesc': 'Encrypted messaging ensures your conversations stay private and secure.',
        'featureSafetyTitle': 'Community Safety Standards',
        'featureSafetyDesc': 'Reporting, blocking, and guidelines create a safe space for everyone.',
        'workflowDiscoverTitle': 'Discover Verified Opportunities',
        'workflowDiscoverDesc': 'Browse verified listings and profiles. Filter by location and season.',
        'workflowConnectTitle': 'Connect with Confidence',
        'workflowConnectDesc': 'Use secure messaging to discuss details and build trust.',
        'workflowSignTitle': 'Sign a Clear Agreement',
        'workflowSignDesc': 'Both parties review and sign a transparent agreement.',
        'workflowStartTitle': 'Start Your Experience',
        'workflowStartDesc': 'Begin your journey and build your verified reputation.',
    },
    'de': {
        'socialProofTitle': 'Vertraut von globalen Saisonniers',
        'socialProofDesc': 'Verifizierte Mitglieder in 50+ Ländern.',
        'verifiedMembers': 'Verifizierte Mitglieder',
        'verifiedListings': 'Verifizierte Angebote',
        'successfulMatches': 'Erfolgreiche Vermittlungen',
        'countriesActive': 'Länder Aktiv',
        'featureVerifiedUsersTitle': 'Verifizierte Benutzer',
        'featureVerifiedUsersDesc': 'Jeder Benutzer wird per E-Mail und Telefon verifiziert.',
        'featureReputationTitle': 'Verifizierter Ruf',
        'featureReputationDesc': 'Jede Interaktion baut Reputation auf.',
        'featureAgreementsTitle': 'Rechtlich klare Vereinbarungen',
        'featureAgreementsDesc': 'Zweisprachige Vereinbarungen mit digitalen Signaturen.',
        'featureCommunicationTitle': 'Globale Kommunikation',
        'featureCommunicationDesc': 'Echtzeit-Übersetzung beseitigt Sprachbarrieren.',
        'featureMessagingTitle': 'Private und sichere Nachrichten',
        'featureMessagingDesc': 'Verschlüsselte Nachrichten bleiben privat und sicher.',
        'featureSafetyTitle': 'Community-Sicherheit',
        'featureSafetyDesc': 'Meldungen und Richtlinien schaffen einen sicheren Ort.',
        'workflowDiscoverTitle': 'Entdecken Sie verifizierte Gelegenheiten',
        'workflowDiscoverDesc': 'Durchsuchen Sie Angebote und Filter nach Ort.',
        'workflowConnectTitle': 'Verbinden Sie sich mit Zuversicht',
        'workflowConnectDesc': 'Sichere Nachrichten zum Besprechen von Details.',
        'workflowSignTitle': 'Unterzeichnen Sie eine klare Vereinbarung',
        'workflowSignDesc': 'Beide Parteien überprüfen und unterzeichnen.',
        'workflowStartTitle': 'Beginnen Sie Ihr Abenteuer',
        'workflowStartDesc': 'Starten Sie Ihre Reise und bauen Sie Ihren Ruf auf.',
    },
    'es': {
        'socialProofTitle': 'De confianza para trabajadores estacionales',
        'socialProofDesc': 'Miembros verificados en 50+ países.',
        'verifiedMembers': 'Miembros Verificados',
        'verifiedListings': 'Listados Verificados',
        'successfulMatches': 'Coincidencias Exitosas',
        'countriesActive': 'Países Activos',
        'featureVerifiedUsersTitle': 'Usuarios Verificados',
        'featureVerifiedUsersDesc': 'Cada usuario se verifica por correo y teléfono.',
        'featureReputationTitle': 'Reputación Verificada',
        'featureReputationDesc': 'Cada interacción construye reputación.',
        'featureAgreementsTitle': 'Acuerdos Legalmente Claros',
        'featureAgreementsDesc': 'Acuerdos bilingües con firmas digitales.',
        'featureCommunicationTitle': 'Comunicación Global',
        'featureCommunicationDesc': 'Traducción en tiempo real elimina barreras.',
        'featureMessagingTitle': 'Mensajería Privada y Segura',
        'featureMessagingDesc': 'Mensajes cifrados permanecen privados.',
        'featureSafetyTitle': 'Seguridad Comunitaria',
        'featureSafetyDesc': 'Denuncias y directrices crean un espacio seguro.',
        'workflowDiscoverTitle': 'Descubra Oportunidades Verificadas',
        'workflowDiscoverDesc': 'Explore listados y filtre por ubicación.',
        'workflowConnectTitle': 'Conecte con Confianza',
        'workflowConnectDesc': 'Mensajería segura para discutir detalles.',
        'workflowSignTitle': 'Firme un Acuerdo Claro',
        'workflowSignDesc': 'Ambas partes revisan y firman.',
        'workflowStartTitle': 'Comience Su Experiencia',
        'workflowStartDesc': 'Inicie su viaje y construya su reputación.',
    },
    'fr': {
        'socialProofTitle': 'De confiance auprès des travailleurs saisonniers',
        'socialProofDesc': 'Membres vérifiés dans 50+ pays.',
        'verifiedMembers': 'Membres Vérifiés',
        'verifiedListings': 'Annonces Vérifiées',
        'successfulMatches': 'Appariements Réussis',
        'countriesActive': 'Pays Actifs',
        'featureVerifiedUsersTitle': 'Utilisateurs Vérifiés',
        'featureVerifiedUsersDesc': 'Chaque utilisateur est vérifié par email et téléphone.',
        'featureReputationTitle': 'Réputation Vérifiée',
        'featureReputationDesc': 'Chaque interaction crée la réputation.',
        'featureAgreementsTitle': 'Accords Légalement Clairs',
        'featureAgreementsDesc': 'Accords bilingues avec signatures numériques.',
        'featureCommunicationTitle': 'Communication Mondiale',
        'featureCommunicationDesc': 'Traduction en temps réel élimine les barrières.',
        'featureMessagingTitle': 'Messagerie Privée et Sécurisée',
        'featureMessagingDesc': 'Les messages chiffrés restent privés.',
        'featureSafetyTitle': 'Sécurité Communautaire',
        'featureSafetyDesc': 'Les signalements créent un espace sûr.',
        'workflowDiscoverTitle': 'Découvrez les Opportunités Vérifiées',
        'workflowDiscoverDesc': 'Parcourez les annonces et filtrez par lieu.',
        'workflowConnectTitle': 'Connectez-vous en Confiance',
        'workflowConnectDesc': 'Messagerie sécurisée pour discuter.',
        'workflowSignTitle': 'Signez un Accord Clair',
        'workflowSignDesc': 'Les deux parties examinent et signent.',
        'workflowStartTitle': 'Commencez Votre Expérience',
        'workflowStartDesc': 'Commencez votre voyage et construisez votre réputation.',
    },
    'it': {
        'socialProofTitle': 'Di fiducia per lavoratori stagionali',
        'socialProofDesc': 'Membri verificati in 50+ paesi.',
        'verifiedMembers': 'Membri Verificati',
        'verifiedListings': 'Annunci Verificati',
        'successfulMatches': 'Abbinamenti Riusciti',
        'countriesActive': 'Paesi Attivi',
        'featureVerifiedUsersTitle': 'Utenti Verificati',
        'featureVerifiedUsersDesc': 'Ogni utente viene verificato per email e telefono.',
        'featureReputationTitle': 'Reputazione Verificata',
        'featureReputationDesc': 'Ogni interazione costruisce reputazione.',
        'featureAgreementsTitle': 'Accordi Legalmente Chiari',
        'featureAgreementsDesc': 'Accordi bilingui con firme digitali.',
        'featureCommunicationTitle': 'Comunicazione Globale',
        'featureCommunicationDesc': 'Traduzione in tempo reale elimina barriere.',
        'featureMessagingTitle': 'Messaggistica Privata e Sicura',
        'featureMessagingDesc': 'I messaggi crittografati rimangono privati.',
        'featureSafetyTitle': 'Sicurezza Comunitaria',
        'featureSafetyDesc': 'Le segnalazioni creano uno spazio sicuro.',
        'workflowDiscoverTitle': 'Scopri Opportunità Verificate',
        'workflowDiscoverDesc': 'Sfoglia annunci e filtra per località.',
        'workflowConnectTitle': 'Connettiti con Fiducia',
        'workflowConnectDesc': 'Messaggistica sicura per discutere.',
        'workflowSignTitle': 'Firma un Accordo Chiaro',
        'workflowSignDesc': 'Entrambe le parti esaminano e firmano.',
        'workflowStartTitle': 'Inizia la Tua Esperienza',
        'workflowStartDesc': 'Inizia il tuo viaggio e costruisci la tua reputazione.',
    },
    'pt': {
        'socialProofTitle': 'De confiança para trabalhadores sazonais',
        'socialProofDesc': 'Membros verificados em 50+ países.',
        'verifiedMembers': 'Membros Verificados',
        'verifiedListings': 'Anúncios Verificados',
        'successfulMatches': 'Correspondências Bem-sucedidas',
        'countriesActive': 'Países Ativos',
        'featureVerifiedUsersTitle': 'Usuários Verificados',
        'featureVerifiedUsersDesc': 'Cada usuário é verificado por email e telefone.',
        'featureReputationTitle': 'Reputação Verificada',
        'featureReputationDesc': 'Cada interação constrói reputação.',
        'featureAgreementsTitle': 'Acordos Legalmente Claros',
        'featureAgreementsDesc': 'Acordos bilíngues com assinaturas digitais.',
        'featureCommunicationTitle': 'Comunicação Global',
        'featureCommunicationDesc': 'Tradução em tempo real remove barreiras.',
        'featureMessagingTitle': 'Mensagens Privadas e Seguras',
        'featureMessagingDesc': 'Mensagens criptografadas permanecem privadas.',
        'featureSafetyTitle': 'Segurança Comunitária',
        'featureSafetyDesc': 'Relatórios criam um espaço seguro.',
        'workflowDiscoverTitle': 'Descubra Oportunidades Verificadas',
        'workflowDiscoverDesc': 'Navegue por anúncios e filtre por local.',
        'workflowConnectTitle': 'Conecte-se com Confiança',
        'workflowConnectDesc': 'Mensagens seguras para discutir.',
        'workflowSignTitle': 'Assine um Acordo Claro',
        'workflowSignDesc': 'Ambas as partes revisam e assinam.',
        'workflowStartTitle': 'Comece Sua Experiência',
        'workflowStartDesc': 'Comece sua jornada e construa sua reputação.',
    },
}

for locale in locales:
    data[locale].update(new_keys[locale])

for locale in locales:
    with open(f'locales/{locale}.json', 'w', encoding='utf-8') as f:
        json.dump(data[locale], f, ensure_ascii=False, indent=2)

print("✅ Added translation keys for components")
