#!/bin/bash

# Vercel Deployment Consolidation Guide
# This helps identify and fix multiple Vercel deployments for the same project

echo "🔍 Checking for multiple Vercel deployments..."
echo ""
echo "To fix 5 separate Vercel deployments, do this:"
echo ""
echo "1. Go to: https://vercel.com/seasoners-organization"
echo ""
echo "2. Check for DUPLICATE PROJECTS with similar names:"
echo "   - seasoners-starter"
echo "   - seasoners-global-launch"
echo "   - Seasoners (or variations)"
echo "   - Any other similar naming"
echo ""
echo "3. For each DUPLICATE project:"
echo "   a) Click the project name"
echo "   b) Go to Settings → General"
echo "   c) Scroll to bottom → DELETE PROJECT"
echo "   d) Confirm deletion"
echo ""
echo "4. KEEP ONLY ONE project:"
echo "   - Primary: seasoners-global-launch (production: www.seasoners.eu)"
echo ""
echo "5. If you see multiple branches deploying:"
echo "   a) Go to project → Settings → Git"
echo "   b) Ensure only 'main' branch is set to Production"
echo "   c) Delete any old branches from GitHub"
echo ""
echo "6. Check for ORPHANED builds:"
echo "   a) Go to project → Deployments"
echo "   b) Look for multiple deployments with different URLs"
echo "   c) Verify all point to www.seasoners.eu"
echo ""
echo "❌ What to DELETE:"
echo "   - Any deployment URLs that aren't www.seasoners.eu"
echo "   - Duplicate projects"
echo "   - Old staging/testing environments"
echo ""
echo "✅ What to KEEP:"
echo "   - One Production deployment: main branch → www.seasoners.eu"
echo "   - Preview deployments: auto-generated from PRs"
echo "   - Development: local npm run dev"
echo ""
echo "Common causes of multiple deployments:"
echo "1. Old project not deleted"
echo "2. Multiple Git branches auto-deploying"
echo "3. Same project added multiple times"
echo "4. Old custom domains"
echo ""
