export type CountryCode = { code: string; name: string; flag?: string; iso?: string };

export const COUNTRY_CODES: CountryCode[] = [
  { code: '+1', name: 'United States', flag: '🇺🇸', iso: 'US' },
  { code: '+1', name: 'Canada', flag: '🇨🇦', iso: 'CA' },
  { code: '+44', name: 'United Kingdom', flag: '🇬🇧', iso: 'GB' },
  { code: '+43', name: 'Austria', flag: '🇦🇹', iso: 'AT' },
  { code: '+49', name: 'Germany', flag: '🇩🇪', iso: 'DE' },
  { code: '+41', name: 'Switzerland', flag: '🇨🇭', iso: 'CH' },
  { code: '+39', name: 'Italy', flag: '🇮🇹', iso: 'IT' },
  { code: '+34', name: 'Spain', flag: '🇪🇸', iso: 'ES' },
  { code: '+33', name: 'France', flag: '🇫🇷', iso: 'FR' },
  { code: '+351', name: 'Portugal', flag: '🇵🇹', iso: 'PT' },
  { code: '+31', name: 'Netherlands', flag: '🇳🇱', iso: 'NL' },
  { code: '+32', name: 'Belgium', flag: '🇧🇪', iso: 'BE' },
  { code: '+45', name: 'Denmark', flag: '🇩🇰', iso: 'DK' },
  { code: '+46', name: 'Sweden', flag: '🇸🇪', iso: 'SE' },
  { code: '+47', name: 'Norway', flag: '🇳🇴', iso: 'NO' },
  { code: '+358', name: 'Finland', flag: '🇫🇮', iso: 'FI' },
  { code: '+353', name: 'Ireland', flag: '🇮🇪', iso: 'IE' },
  { code: '+420', name: 'Czechia', flag: '🇨🇿', iso: 'CZ' },
  { code: '+421', name: 'Slovakia', flag: '🇸🇰', iso: 'SK' },
  { code: '+36', name: 'Hungary', flag: '🇭🇺', iso: 'HU' },
  { code: '+48', name: 'Poland', flag: '🇵🇱', iso: 'PL' },
  { code: '+40', name: 'Romania', flag: '🇷🇴', iso: 'RO' },
  { code: '+359', name: 'Bulgaria', flag: '🇧🇬', iso: 'BG' },
  { code: '+385', name: 'Croatia', flag: '🇭🇷', iso: 'HR' },
  { code: '+386', name: 'Slovenia', flag: '🇸🇮', iso: 'SI' },
  { code: '+381', name: 'Serbia', flag: '🇷🇸', iso: 'RS' },
  { code: '+387', name: 'Bosnia & Herzegovina', flag: '🇧🇦', iso: 'BA' },
  { code: '+389', name: 'North Macedonia', flag: '🇲🇰', iso: 'MK' },
  { code: '+355', name: 'Albania', flag: '🇦🇱', iso: 'AL' },
  { code: '+30', name: 'Greece', flag: '🇬🇷', iso: 'GR' },
  { code: '+90', name: 'Türkiye', flag: '🇹🇷', iso: 'TR' },
  { code: '+380', name: 'Ukraine', flag: '🇺🇦', iso: 'UA' },
  { code: '+972', name: 'Israel', flag: '🇮🇱', iso: 'IL' },
  { code: '+971', name: 'United Arab Emirates', flag: '🇦🇪', iso: 'AE' },
  { code: '+966', name: 'Saudi Arabia', flag: '🇸🇦', iso: 'SA' },
  { code: '+20', name: 'Egypt', flag: '🇪🇬', iso: 'EG' },
  { code: '+212', name: 'Morocco', flag: '🇲🇦', iso: 'MA' },
  { code: '+27', name: 'South Africa', flag: '🇿🇦', iso: 'ZA' },
  { code: '+234', name: 'Nigeria', flag: '🇳🇬', iso: 'NG' },
  { code: '+254', name: 'Kenya', flag: '🇰🇪', iso: 'KE' },
  { code: '+91', name: 'India', flag: '🇮🇳', iso: 'IN' },
  { code: '+92', name: 'Pakistan', flag: '🇵🇰', iso: 'PK' },
  { code: '+880', name: 'Bangladesh', flag: '🇧🇩', iso: 'BD' },
  { code: '+94', name: 'Sri Lanka', flag: '🇱🇰', iso: 'LK' },
  { code: '+60', name: 'Malaysia', flag: '🇲🇾', iso: 'MY' },
  { code: '+65', name: 'Singapore', flag: '🇸🇬', iso: 'SG' },
  { code: '+62', name: 'Indonesia', flag: '🇮🇩', iso: 'ID' },
  { code: '+63', name: 'Philippines', flag: '🇵🇭', iso: 'PH' },
  { code: '+66', name: 'Thailand', flag: '🇹🇭', iso: 'TH' },
  { code: '+84', name: 'Vietnam', flag: '🇻🇳', iso: 'VN' },
  { code: '+81', name: 'Japan', flag: '🇯🇵', iso: 'JP' },
  { code: '+82', name: 'South Korea', flag: '🇰🇷', iso: 'KR' },
  { code: '+86', name: 'China', flag: '🇨🇳', iso: 'CN' },
  { code: '+886', name: 'Taiwan', flag: '🇹🇼', iso: 'TW' },
  { code: '+852', name: 'Hong Kong', flag: '🇭🇰', iso: 'HK' },
  { code: '+853', name: 'Macau', flag: '🇲🇴', iso: 'MO' },
  { code: '+61', name: 'Australia', flag: '🇦🇺', iso: 'AU' },
  { code: '+64', name: 'New Zealand', flag: '🇳🇿', iso: 'NZ' },
  { code: '+52', name: 'Mexico', flag: '🇲🇽', iso: 'MX' },
  { code: '+55', name: 'Brazil', flag: '🇧🇷', iso: 'BR' },
  { code: '+54', name: 'Argentina', flag: '🇦🇷', iso: 'AR' },
  { code: '+56', name: 'Chile', flag: '🇨🇱', iso: 'CL' },
  { code: '+57', name: 'Colombia', flag: '🇨🇴', iso: 'CO' },
  { code: '+51', name: 'Peru', flag: '🇵🇪', iso: 'PE' },
  { code: '+593', name: 'Ecuador', flag: '🇪🇨', iso: 'EC' },
  { code: '+598', name: 'Uruguay', flag: '🇺🇾', iso: 'UY' },
  { code: '+595', name: 'Paraguay', flag: '🇵🇾', iso: 'PY' },
  { code: '+591', name: 'Bolivia', flag: '🇧🇴', iso: 'BO' },
  { code: '+58', name: 'Venezuela', flag: '🇻🇪', iso: 'VE' },
];
